<?php

return [
    [
        "categories" => [2],
        "name" => "Haruka Sushi",
        "user_id"       => "1",
        "description" => "Esperienza culinaria incantata: Il nostro ristorante trasforma ingredienti ordinari in opere d'arte gustative, incantando i palati con un connubio magico di sapori e presentazioni uniche.",
        "city" => "Milano",
        "address" => "Corso San Gottardo, 49",
        "vat" => "2389176594",
        "url_image" => "uploads/restaurant/giapponese-ristorante.jpg",
        "priceRange" => 35,
        "rating_value" => 9,
        "review_count" => 150,
    ],
    // [
    //     "categories" => [1, 4],
    //     "name" => "Slice",
    //     "user_id"       => "2",
    //     "description" => "Gusto del Futuro: Benvenuti nel ristorante dove la cucina innovativa abbraccia la tradizione, creando un viaggio gastronomico senza confini.",
    //     "city" => "Milano",
    //     "address" => "Via Giovanni Gherardini, 2",
    //     "vat" => "5098237461",
    //     "url_image" => "uploads/rest02.jpg",
    //     "priceRange" => 25,
    //     "rating_value" => 8,
    //     "review_count" => 267,
    // ],
    [
        "categories" => [1, 4],
        "name" => "Il Fiore all'Occhiello",
        "user_id"       => "2",
        "description" => "Sapore Avventuroso, Destinazione Gustosa: Esplora i confini culinari mentre il nostro ristorante ti guida attraverso un mondo di sapori inaspettati e delizie straordinarie.",
        "city" => "Roma",
        "address" => "Via Costantino, 24",
        "vat" => "7168943025",
        "url_image" => "uploads/restaurant/Pizza-ristorante.jpg",
        "priceRange" => 28,
        "rating_value" => 9,
        "review_count" => 7337,
    ],
    [
        "categories" => [1, 3],
        "name" => "Quarantuno Restaurant",
        "user_id"       => "3",
        "description" => "Ristorante Etereo: Dove i desideri gastronomici prendono vita, con piatti che sembrano provenire da un mondo incantato e profumi che raccontano storie dimenticate.",
        "city" => "Roma",
        "address" => "Via Ostiense, 39-41",
        "vat" => "6250193847",
        "url_image" => "uploads/restaurant/ristorante-vegetariano.jpg",
        "priceRange" => 25,
        "rating_value" => 8,
        "review_count" => 592,
    ],
    [
        "categories" => [1, 3],
        "name" => "San Paolino",
        "user_id"       => "4",
        "description" => "Gastronomia in 4D: Nel nostro ristorante, i piatti non sono solo da gustare ma da vivere, con un'esperienza multisensoriale che sorprende e incanta.",
        "city" => "Firenze",
        "address" => "Via Palazzuolo, 9A",
        "vat" => "4382759016",
        "url_image" => "uploads/restaurant/vegan-ristorante.jpg",
        "priceRange" => 35,
        "rating_value" => 9,
        "review_count" => 352,
    ],
    // [
    //     "categories" => [1, 4],
    //     "name" => "Oliandolo Caffè Ristoro",
    //     "user_id"       => "6",
    //     "description" => "Racconti di Sapori: Ogni piatto nel nostro locale racconta una storia unica, intrecciando ingredienti e creatività in un'esperienza culinaria da ricordare.",
    //     "city" => "Firenze",
    //     "address" => "Via Ricasoli, 38/40 R",
    //     "vat" => "9016325847",
    //     "url_image" => "uploads/rest06.jpg",
    //     "priceRange" => 32,
    //     "rating_value" => 4,
    //     "review_count" => 193,
    // ],
    [
        "categories" => [1],
        "name" => "Casa Merlò",
        "user_id"       => "5",
        "description" => "Sinfonia di Sapori: Il nostro ristorante è un palcoscenico dove i gusti si fondono in un'armonia perfetta, creando una sinfonia di sapori indimenticabile.",
        "city" => "Bologna",
        "address" => "Via de' Gombruti, 2/D",
        "vat" => "7843569021",
        "url_image" => "uploads/restaurant/ristorante-italiano.jpg",
        "priceRange" => 30,
        "rating_value" => 5,
        "review_count" => 63,
    ],
    [
        "categories" => [1],
        "name" => "Capriccio",
        "user_id"       => "6",
        "description" => "Rivoluzione del Gusto: Entra nel futuro della cucina, dove la scienza e l'arte si fondono per creare piatti rivoluzionari che sfidano ogni aspettativa.",
        "city" => "Bologna",
        "address" => "Via Domodossola, 3",
        "vat" => "3129456780",
        "url_image" => "uploads/restaurant/restaurant-ita.jpg",
        "priceRange" => 35,
        "rating_value" => 6,
        "review_count" => 114,
    ],
    [
        "categories" => [1],
        "name" => "Terrazza Merliani 2.0",
        "user_id"       => "7",
        "description" => "Ristorante Spezzato dal Tempo: Un luogo dove passato, presente e futuro si incontrano nel piatto, creando un'esperienza senza tempo che delizia i sensi.",
        "city" => "Napoli",
        "address" => "Via Giovanni Merliani, 73",
        "vat" => "5672309184",
        "url_image" => "uploads/restaurant/A-Milano.jpg",
        "priceRange" => 15,
        "rating_value" => 9,
        "review_count" => 415,
    ],
    // [
    //     "categories" => [4],
    //     "name" => "Nam 43",
    //     "user_id"       => "10",
    //     "description" => "Sapori Nascosti: Scopri il lato segreto della cucina, dove ingredienti insoliti si rivelano in piatti straordinari che stupiscono anche i palati più esperti.",
    //     "city" => "Napoli",
    //     "address" => "Via Santa Maria di Costantinopoli, 43",
    //     "vat" => "1248703569",
    //     "url_image" => "uploads/rest10.jpg",
    //     "priceRange" => 15,
    //     "rating_value" => 7,
    //     "review_count" => 431,
    // ],
    [
        "categories" => [5],
        "name" => "Locanda dei Buoni e Cattivi",
        "user_id"       => "8",
        "description" => "Caleidoscopio Culinario: Il nostro ristorante è un viaggio attraverso colori, forme e gusti in continua evoluzione, offrendo un'esperienza visiva e gustativa unica.",
        "city" => "Cagliari",
        "address" => "Via Vittorio Veneto, 96",
        "vat" => "8950341627",
        "url_image" => "uploads/restaurant/ristorante-messicano.jpg",
        "priceRange" => 25,
        "rating_value" => 4,
        "review_count" => 480,
    ],
    // [
    //     "categories" => [1, 4],
    //     "name" => "Obicà  Mozzarella Bar",
    //     "user_id"       => "12",
    //     "description" => "Ristorante degli Inganni: Nulla è come sembra in questo mondo di illusioni gastronomiche, dove i piatti sfidano la percezione e stupiscono ogni ospite.",
    //     "city" => "Cagliari",
    //     "address" => "Via Roma, 143",
    //     "vat" => "6701589324",
    //     "url_image" => "uploads/rest12.jpg",
    //     "priceRange" => 24,
    //     "rating_value" => 9,
    //     "review_count" => 101,
    // ],
];
